# Generated by Django 3.1 on 2020-08-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyablog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Gender',
        ),
    ]
